GET http://127.0.0.1:5000/api/users

###

GET http://127.0.0.1:5000/api/user/960c883e-353d-4aa5-ba3c-cd6da55001c0

###

POST http://127.0.0.1:5000/api/user
content-type: application/x-www-form-urlencoded

login=pepe
&password=p
&type=normal

###

POST http://127.0.0.1:5000/api/user/authenticate
content-type: application/x-www-form-urlencoded

login=adolfo
&password=a

###

POST http://127.0.0.1:5000/api/user/authenticate-administrator
content-type: application/x-www-form-urlencoded

login=adolfo
&password=a

###

GET http://127.0.0.1:5000/api/users 
Content-Type: application/x-www-form-urlencoded 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6ImFkb2xmbyIsInJlbW90ZUFkZHJlc3MiOiI6OmZmZmY6MTI3LjAuMC4xIiwidHlwZSI6ImFkbWluaXN0cmF0b3IiLCJpYXQiOjE2MTk2MjU1NTEsImV4cCI6MTYxOTcwOTU1MX0._ISiIbezJslyLLBDpFCJMY3sidYkw8t0070Ato92tV4