GET http://127.0.0.1:5000/api/users

###

GET http://127.0.0.1:5000/api/user/960c883e-353d-4aa5-ba3c-cd6da55001c0

###

POST http://127.0.0.1:5000/api/user
content-type: application/x-www-form-urlencoded

login=pepe
&password=p

###

POST http://127.0.0.1:5000/api/useropen
content-type: application/x-www-form-urlencoded

login=pepe
&password=p